### ISSUE TITLE
Calculate AC Charge Cutoff %

### ISSUE THREAD

**Issue by woopstar** [woopstar/hsem#40]
Something like this:

```yaml
required_charge: "{{ [total_energy_need - current_battery_capacity + battery_min_capacity, 0] | max }}"

required_charge_adjusted: "{{ [required_charge, usable_battery_capacity] | min }}"

required_grid_charge: "{{ [required_charge_adjusted - total_charging_headroom, 0] | max | float(0) }}"

ac_charge_cutoff_percentage: "{{ ((required_grid_charge / battery_max_capacity * 100) + (battery_min_capacity / battery_max_capacity * 100)) | round(0) | float(0) }}"
```
